name: manga2021
channels:
  - conda-forge
  - defaults
dependencies:
  - black=20.8b1
  - h5py>=3.1.0
  - ipympl>=0.6.3
  - jupyterlab>=3.0.6
  - jupyterlab_code_formatter>=1.4.2
  - lxml
  - matplotlib>=3.3.4
  - mypy>=0.790
  - numpy>=1.20.1
  - opencv
  - pip
  - pylint
  - python
  - pytorch
  - rope
  - scipy>=1.6.1
  - scikit-image
  - tensorflow
  - tqdm
  - pip:
      - manga109api
